version: 0.0
os: linux
files:
  - source: server.zip
    destination: /app  # Extracts server folder inside /app

hooks:
  BeforeInstall:
    - location: server/scripts/stop-server.sh
      runas: root
      timeout: 300

  AfterInstall:
    - location: server/scripts/install-dependencies.sh
      runas: root
      timeout: 300
    - location: server/scripts/start-server.sh
      runas: root
      timeout: 300
