version: 0.0
os: linux
files:
  - source: server.zip
    destination: /app  # Extracts server folder inside /app
  - source: scripts/
    destination: /app/scripts 
  - source: package.json
    destination: /app
  - source: package-lock.json
    destination: /app

hooks:
  BeforeInstall:
    - location: /scripts/stop-server.sh
      runas: root
      timeout: 300

  AfterInstall:
    - location: /scripts/install-dependencies.sh
      runas: root
      timeout: 300
    - location: /scripts/start-server.sh
      runas: root
      timeout: 300
